[workspace]
authors = ["tsoysergey24 <74559499+tsoysergey24@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "codespace"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
jupyterlab = ">=4.6.4,<5"
xeus-r = ">=0.11.2,<0.12"
r-tidyverse = ">=2.0.0,<3"
r-palmerpenguins = ">=0.1.1,<0.2"
